### ISSUE TITLE
WebShell存在无法获取密钥，可能是URL会自动跳转到login页面，怎么办

### ISSUE THREAD

**Issue by rootGH** [4nth0ny1130/spring4shell_behinder#1]

**Comment by 4nth0ny1130** [comment]
本地写了个demo测试了一下，冰蝎判断webshell的逻辑似乎是直接判断webshell的地址状态码是否为200，有重定向就跟过去再判断是否为200，是200就POST数据尝试连接，交互失败就返回无法获取密钥。
你这种情况应该是目标站点做了URL路由白名单，可以初步判断为攻击失败

**Comment by rootGH** [comment]
> 本地写了个demo测试了一下，冰蝎判断webshell的逻辑似乎是直接判断webshell的地址状态码是否为200，有重定向就跟过去再判断是否为200，是200就POST数据尝试连接，交互失败就返回无法获取密钥。 你这种情况应该是目标站点做了URL路由白名单，可以初步判断为攻击失败

目标是个后台，会跳转login登陆页

**Comment by 4nth0ny1130** [comment]
> > 本地写了个demo测试了一下，冰蝎判断webshell的逻辑似乎是直接判断webshell的地址状态码是否为200，有重定向就跟过去再判断是否为200，是200就POST数据尝试连接，交互失败就返回无法获取密钥。 你这种情况应该是目标站点做了URL路由白名单，可以初步判断为攻击失败
> 
> 目标是个后台，会跳转login登陆页

判断攻击是否成功和目标路径没有关系，重点是你这种情况一般是webshell的路径被filter模糊匹配拦截掉之后重定向到了某个页面，冰蝎误把重定向的页面返回的200当成访问webshell返回的200了，所以告诉你获取密钥失败，实际上要么没写进去要么写进去了但无法访问，可以认为攻击失败了。可以手动用无伤检测验证一下，虽然无伤检测可能有误报就是了

**Comment by fumengze** [comment]
@4nth0ny1130 同样遇到了误报的问题，大佬可以留个QQ交流下吗？
