### ISSUE TITLE
给出了shell地址访问是404

### ISSUE THREAD

**Issue by ymbzd** [4nth0ny1130/spring4shell_behinder#2]
给出了shell地址访问是404
![image](https://user-images.githubusercontent.com/39881690/173040585-a3be0c38-d54b-4eb2-9fb1-faf066bb479a.png)
![image](https://user-images.githubusercontent.com/39881690/173040698-f0960359-8c6b-4492-b241-5bc5c9376992.png)

**Comment by 4nth0ny1130** [comment]
脚本判断webshell是否存在的逻辑是访问这个webshell然后检查后端返回的状态码是否为200,我猜测你这种情况应该是后端接收这个请求之后把这个请求交给了某个API处理,然后API处理不了这个请求返回了错误码,这种情况下HTTP返回的状态码是永远是200 OK,导致了脚本误报,实际可能不存在漏洞
